### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by IgorGalimski** [devtodev-analytics/package_Analytics#7]
Hello!
I am trying to build with the latest version 3.8.0, Unity 2021.3.26 and Xcode 15.3 and it failes
<img width="1716" alt="1" src="https://github.com/devtodev-analytics/package_Analytics/assets/19680568/9c4aa733-1229-49d4-b6b7-22dcc6b850f1">

I tried different linker flags - didn't help

Also, I've tried the previous version - but it fails of the unity stage
<img width="1707" alt="Screenshot 2024-04-03 at 10 43 48" src="https://github.com/devtodev-analytics/package_Analytics/assets/19680568/9ef98709-bf6d-47af-b60f-a1631a7112df">

what can be the reason of issue with 3.8.0 version?

**Comment by kaikristo** [comment]
Can you try v3.8.1?

**Comment by IgorGalimski** [comment]
I have other issue on 3.8.1
<img width="679" alt="Screenshot 2024-05-07 at 15 11 32" src="https://github.com/devtodev-analytics/package_Analytics/assets/19680568/cd19005c-cd1a-4903-b7ea-ce6e5f43405f">


Unity 2021.3.24f1, Xcode 15.3

**Comment by kaikristo** [comment]
fixed in v3.8.2

**Comment by IgorGalimski** [comment]
3.8.2 - not fixed


<img width="637" alt="Screenshot 2024-05-09 at 08 41 43" src="https://github.com/devtodev-analytics/package_Analytics/assets/19680568/e06900aa-3164-4632-8e71-3508a212f2a5">
